baseURL: "https://siyisunrr.github.io/"
title: "SIYI SUN"
languageCode: zh-cn
copyright: "Siyi Sun"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  profileMode:
    enabled: true
    title: "Siyi Sun 孙思毅"
    subtitle: >
      B.Eng. in Materials Science @ <img src="/images/logos/njupt.png" class="inline-logo"> **[Nanjing University of Posts and Telecommunications (NJUPT)](https://www.njupt.edu.cn/)**.<br>
      Incoming M.S. in Materials Science @ <img src="/images/logos/thu.png" class="inline-logo"> **[Tsinghua University SIGS (THU)](https://www.sigs.tsinghua.edu.cn/)**.<br>
      Summer School @ <img src="/images/logos/manchester.png" class="inline-logo"> **[The University of Manchester](https://www.manchester.ac.uk/)**.<br>
      Visiting Student @ **[Nanophotonics Materials Lab](https://pengsy.lab.westlake.edu.cn/)**, <img src="/images/logos/westlake.png" class="inline-logo"> [Westlake University](https://www.westlake.edu.cn/).<br><br>
      *Research Interest:* Optoelectronic Materials & NanoPhotonics<br><br>
      [noahsun119@gmail.com](mailto:noahsun119@gmail.com) / [Blog](/posts/)
    imageUrl: "images/homepage_pic.jpg"
    imageTitle: "Siyi Sun"
    imageCaption: "(at Shuangqiao Valley, Mount Siguniang, China)"

  socialIcons:
    - name: github
      url: "https://github.com/siyisunrr"
    - name: email
      url: "mailto:noahsun119@gmail.com"

  author: ["Siyi Sun"]
  defaultTheme: auto
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true

menu:
  main: []
