baseURL: "https://siyisunrr.github.io/"
title: "SIYI SUN"
languageCode: zh-cn
copyright: "Siyi Sun"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

params:
  profileMode:
    enabled: true
    title: "Siyi Sun &nbsp; 孙思毅"
    subtitle: >
      B.Eng. in Materials Science @ [Nanjing University of Posts and Telecommunications (NJUPT)](https://www.njupt.edu.cn/)<br>
      Incoming M.S. in Materials Science @ [Tsinghua University (THU)](https://www.tsinghua.edu.cn/)<br>
      Research Interest: Optoelectronic Materials & NanoPhotonics
    imageUrl: "/images/profile.jpg"
    imageWidth: 180
    imageHeight: 180

    buttons:
      - name: About Me
        url: "/about"
      - name: Blog
        url: "/posts/"

  socialIcons:
    - name: github
      url: "https://github.com/siyisunrr"
    - name: email
      url: "mailto:noahsun119@gmail.com"

  author: ["Siyi Sun"]
  defaultTheme: auto
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true

menu:
  main:
    - identifier: posts
      name: 博客
      url: /posts/
      weight: 10
    - identifier: portfolio
      name: 作品集
      url: /portfolio/
      weight: 20
    - identifier: tags
      name: 标签
      url: /tags/
      weight: 30
    - identifier: search
      name: 搜索 🔍
      url: /search/
      weight: 40
